{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mem0.fullname" . }}
  labels:
    {{- include "mem0.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "mem0.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- range .Values.networkPolicy.policyTypes }}
    - {{ . }}
    {{- end }}
  {{- if has "Ingress" .Values.networkPolicy.policyTypes }}
  ingress:
    # Allow traffic from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000
    # Allow traffic from Prometheus for monitoring
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 8000
    # Allow traffic within the same namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: 8000
  {{- end }}
  {{- if has "Egress" .Values.networkPolicy.policyTypes }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow HTTPS outbound (for OpenAI API)
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Allow HTTP outbound
    - to: []
      ports:
        - protocol: TCP
          port: 80
    {{- if .Values.postgresql.enabled }}
    # Allow PostgreSQL access
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 5432
    {{- end }}
    {{- if .Values.neo4j.enabled }}
    # Allow Neo4j access
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: neo4j
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 7687
        - protocol: TCP
          port: 7474
    {{- end }}
  {{- end }}
{{- end }}